# Generated by Django 4.1.2 on 2022-10-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="New!", max_length=255)),
                ("content", models.TextField()),
                ("version", models.PositiveIntegerField()),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
