# Generated by Django 4.1.2 on 2022-10-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notices", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notice",
            name="version",
            field=models.PositiveIntegerField(blank=True, unique=True),
        ),
    ]
