# Generated by Django 4.1.2 on 2023-07-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notices", "0002_alter_notice_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="notice",
            name="timeout_seconds",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
