# Generated by Django 4.1.2 on 2023-07-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notices", "0003_notice_timeout_seconds"),
    ]

    operations = [
        migrations.AddField(
            model_name="notice",
            name="starts_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
